#!/usr/bin/python
from Adafruit_MotorHAT import Adafruit_MotorHAT, Adafruit_DCMotor

import time
import atexit
# create a default object, no changes to I2C address or frequency
mh = Adafruit_MotorHAT(addr=0x60)
# recommended for auto-disabling motors on shutdown!
def turnOffMotors():
	mh.getMotor(1).run(Adafruit_MotorHAT.RELEASE)
	mh.getMotor(2).run(Adafruit_MotorHAT.RELEASE)
	mh.getMotor(3).run(Adafruit_MotorHAT.RELEASE)
	mh.getMotor(4).run(Adafruit_MotorHAT.RELEASE)

atexit.register(turnOffMotors)
myMotor = mh.getMotor(3)

def running(speedset):
    print "Forward! "
    myMotor.run(Adafruit_MotorHAT.FORWARD)

    print "\tSpeed up..."
    for i in range(speedset):
        myMotor.setSpeed(i)
        time.sleep(0.01)

    while True:
        time.sleep(1)


try:
    while True:
        speedset = raw_input("Set speed: ")
        try:
            speedset = int(speedset)
            if 0 <= speedset <= 255:
                running(speedset)
        except:
            pass

except KeyboardInterrupt:
	pass

finally:
    print "Release"
    myMotor.run(Adafruit_MotorHAT.RELEASE)
    time.sleep(0.1)
